#!/usr/bin/env python3

from sys import *

from src import utils
from src import pivots
from src import matrix as mx

def main():
    try:
        nTab, pTab = utils.argsGetter()
        utils.ArgsChecker(nTab, pTab)
        print("Resources: {:.0f} F1, {:.0f} F2, {:.0f} F3, {:.0f} F4".format(*nTab), end="\n\n")
        matrix = mx.matrixCreate(nTab, pTab)
        res = pivots.doSimplex(matrix)
        tmp = ["0"] * 5
        a = 0
        for i in range(0, 4):
            if res[i] != -1:
                if matrix[i][-1] != 0:
                    tmp[res[i]] = "{:.2f}".format(matrix[i][-1])
                    a += matrix[i][-1] * pTab[res[i]]
                else:
                    tmp[res[i]] = "{:.0f}".format(matrix[i][-1])
        utils.resultPrint(tmp, pTab, a)
    except BaseException as e:
        exit(84)

main()